# Generated by Django 2.0.3 on 2019-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='bill_number',
        ),
        migrations.AddField(
            model_name='bills',
            name='bill_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
