# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Business_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Industry',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='JP_paybill',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Town',
            field=models.CharField(max_length=20),
        ),
    ]
