# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20190925_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='Physical_address',
            field=models.CharField(max_length=60),
        ),
    ]
