# Generated by Django 2.0.12 on 2019-10-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20191009_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterRecipientss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
