# Generated by Django 2.0.3 on 2019-10-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20191004_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='generated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='universal_billing_system.Merchant'),
        ),
    ]
