# Generated by Django 2.0.3 on 2019-10-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20191013_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='due_date',
        ),
    ]
