# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20190925_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='Merchant',
        ),
        migrations.AddField(
            model_name='industry',
            name='name',
            field=models.CharField(default='JamboPay', max_length=40),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='Industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universal_billing_system.Industry'),
        ),
    ]
