# Generated by Django 2.0.3 on 2019-10-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0003_auto_20191004_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='generated_by',
            field=models.CharField(max_length=255),
        ),
    ]
