# Generated by Django 2.0.12 on 2019-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0003_newsletterrecipientss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(help_text='Due date'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
