# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0003_auto_20190925_1019'),
        ('universal_billing_system', '0003_auto_20190925_0947'),
    ]

    operations = [
    ]
