# Generated by Django 2.0.12 on 2019-10-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0004_auto_20191014_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
