# Generated by Django 2.0.3 on 2019-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0004_auto_20191004_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[(0, 'Unpaid'), (1, 'Paid')], default='Unpaid', max_length=10),
        ),
    ]
