# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0005_auto_20190925_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='JamboPay', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Revstreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='JamboPay', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='merchant',
            name='Category',
            field=models.ManyToManyField(to='universal_billing_system.Category'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='Revstreams',
            field=models.ManyToManyField(to='universal_billing_system.Revstreams'),
        ),
    ]
