# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0006_auto_20190925_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=255)),
                ('Revstreams', models.CharField(max_length=255)),
                ('narration', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('quantity', models.FloatField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='town',
            name='Merchant',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
