# Generated by Django 2.0.12 on 2019-10-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0005_auto_20191014_1737'),
        ('universal_billing_system', '0006_auto_20191015_1043'),
    ]

    operations = [
    ]
